#!/bin/bash
# Auto-generated by install.sh -- launches NaiTRO using its own venv.
cd "/home/vishwamanava/NaiTRO/naitro-pc-assistant-main"
exec "/home/vishwamanava/NaiTRO/naitro-pc-assistant-main/venv/bin/python" "/home/vishwamanava/NaiTRO/naitro-pc-assistant-main/Python/naitro_app.py"
